# Generated by Django 4.0.1 on 2022-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_author_blog_period_alter_blog_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
    ]
